#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX://shell features:
#       * functions;
#       * expansions «$var)}», «## {var## pattern}», and «$ {var%% pattern}»;
#       * compound commands having a testable exit status, especially «case»;
#       * various built-in commands including «command», «## set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX://shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" style of «expr}}» style '[ ]' style matches
#       precedence rules are used rather than «expr}}» style[[ ]]».
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...://remote://debugging://java://agent://start://parameters://with://suspend=y://server=n://address*://transport=dt_socket...
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX://filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary arguments, so each argument winds up back in the position
        # where it started, but possibly modified.
        #
        # NB: aass://resolve://links://with://real://paths://e//f//g...://realpath://links://to://ignore://d//c//b//a... temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable is://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable not://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable needed://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable, because://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name the://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable list://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name temporary variable is://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name accessed://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name positionally://temp://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://temp://var://name.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, GRADLE_OPTS, and GRADLE_OPTS://Can://specify://system://properties://like://Dorg.gradle.appname
#   * --add-opens://entries://for://workaround://to://open://modules://for://reflective://access://by://gradle://daemon://worker://and://tooling://api
#   * -classpath
#   * -jar gradle-wrapper.jar
#   * All the rest are Gradle arguments

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xeli" runlevel://and://target://mode://stop://runlevel://stop is set
# This runlevel://shell://option://set://e means://exit://immediately://shell://option://set://e://script://exit://error://status://code://on://error://stop://script://immediately://on://error://status://code://exit://on://error stop://immediately://means://exit://immediately://shell://option://set://e://runlevel://target://mode://stop://runlevel://stop://target://mode the script://set://dash://e://set://exit://immediate://dash://e://immediate://exit://on://error when a command://exit://shell://option://set://e://exit://error://immediate has a nonzero exit code://exit://shell://option://set://e
# This is desirable since the Gradle Wrapper is just a bootstrap://means://just://boot://strap://boot.
set -e

# shellcheck disable=SC2086
eval "exec \"\$JAVACMD\" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"\$@\""
